name: pytest

on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        run: |
          git clone https://github.com/YZXBiz/python-demo
          cd python-demo

      - name: pip install
        run: pip install -r python-demo/requirements.txt

      - name: run pytest
        run: pytest python-demo/tests/test.py
