name: pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: pip install
        run: |
          ls -l
          pip install -r requirements.txt

      - name: run pytest
        run: pytest .
