name: pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        run: |
          git clone https://github.com/YZXBiz/python-demo
          cd python-demo

      - name: pip install
        run: |
          cd python-demo
          ls -l 
          pip install -r requirements.txt

      - name: run pytest
        run: |
          cd python-demo
          pytest .
